### ISSUE TITLE
Usage of new Update function 

### ISSUE THREAD

**Issue by nOmi7** [processone/cache_tab#7]
@zinid  Thanks for re-writing module to update cache.
What is the importance of UpdateFun () ?  when i am passing value with key in update func.
UpdateFun should always return ok  to update the values ?
Can you please help me with small example of update usage ?

**Comment by nOmi7** [comment]
`ets_cache:update(graph_cache,123,#graph{id = 123 , val=2342},fun() -> ok end)`

**Comment by zinid** [comment]
The `Val` should be in the form of `{ok, V}` or `error`. If existing value in the cache matches `Val` then `UpdateFun` is not called. Otherwise `UpdateFun` is called and should return `ok` (otherwise the cache will not be updated).
**Example 1**: you want to write value `a` at key `1`:
```erlang
ets_cache:update(my_tab, 1, {ok, a}, fun() -> database_write(1, a), ok end).
```
In the example above `database_write(1, a)` is not called if there is already value `a` associated with the key `1`.
**Example 2**: you want to delete value `b` associated with key `2`:
```erlang
ets_cache:update(my_tab, 2, error, fun() -> database_delete(2), ok end).
```
In this case function `database_delete(2)` won't be called if there is already `error` in the cache (i.e. 'miss' is associated with key `2` in the cache).

**Comment by zinid** [comment]
So, simply put, `ets_cache:update()` function serves two purposes:
1. Writing/deleting database data with cache updates.
2. Avoiding excessive writes/deletes for the same data.

**Comment by nOmi7** [comment]
Great .. and thanks @zinid
